import type { User, Team, Ticket } from '@/lib/types';

export const users: User[] = [
  { id: 'user-alex', name: 'Alex Johnson', email: 'alex@triageflow.com', avatarUrl: 'https://i.pravatar.cc/150?u=alex', teamId: 'team-tech' },
  { id: 'user-bob', name: 'Bob Williams', email: 'bob@triageflow.com', avatarUrl: 'https://i.pravatar.cc/150?u=bob', teamId: 'team-tech' },
  { id: 'user-charlie', name: 'Charlie Brown', email: 'charlie@triageflow.com', avatarUrl: 'https://i.pravatar.cc/150?u=charlie', teamId: 'team-billing' },
  { id: 'user-diana', name: 'Diana Prince', email: 'diana@triageflow.com', avatarUrl: 'https://i.pravatar.cc/150?u=diana', teamId: 'team-sales' },
];

export const teams: Team[] = [
  { id: 'team-tech', name: 'Technical Support' },
  { id: 'team-billing', name: 'Billing' },
  { id: 'team-sales', name: 'Sales' },
  { id: 'team-general', name: 'General Inquiries' },
];

export const tickets: Ticket[] = [
  {
    id: 'TKT-001',
    subject: 'Cannot login to my account',
    description: 'I am trying to log in with my credentials but it keeps saying "Invalid password". I have tried resetting it but did not receive an email. Please help.',
    customerName: 'Alice Martin',
    customerEmail: 'alice.m@example.com',
    status: 'escalated',
    urgency: 'high',
    category: 'Technical',
    assignedTo: users[0],
    team: teams[0],
    createdAt: '2024-08-10T10:00:00Z',
    logs: [
      { id: 'log-1-1', timestamp: '2024-08-10T09:00:00Z', actor: 'AI', actorName: 'TriageFlow AI', action: 'Ticket Created', details: 'Received from email.' },
      { id: 'log-1-2', timestamp: '2024-08-10T09:01:00Z', actor: 'AI', actorName: 'TriageFlow AI', action: 'Intent Analysis', details: 'Intent: Login Issue, Urgency: High, Category: Technical' },
      { id: 'log-1-3', timestamp: '2024-08-10T09:02:00Z', actor: 'AI', actorName: 'TriageFlow AI', action: 'Route & Escalate', details: 'Assigned to Alex Johnson (Technical Support) and marked as escalated.' },
    ],
  },
  {
    id: 'TKT-002',
    subject: 'Question about my recent invoice',
    description: 'Hi, I was charged twice for my subscription this month. Can you please look into it and issue a refund for the extra charge?',
    customerName: 'John Doe',
    customerEmail: 'john.d@example.com',
    status: 'in_progress',
    urgency: 'medium',
    category: 'Billing',
    assignedTo: users[2],
    team: teams[1],
    createdAt: '2024-08-10T11:30:00Z',
    logs: [
      { id: 'log-2-1', timestamp: '2024-08-10T11:30:00Z', actor: 'AI', actorName: 'TriageFlow AI', action: 'Ticket Created', details: 'Received from API.' },
      { id: 'log-2-2', timestamp: '2024-08-10T11:31:00Z', actor: 'AI', actorName: 'TriageFlow AI', action: 'Intent Analysis', details: 'Intent: Billing Inquiry, Urgency: Medium, Category: Billing' },
      { id: 'log-2-3', timestamp: '2024-08-10T11:32:00Z', actor: 'AI', actorName: 'TriageFlow AI', action: 'Route Ticket', details: 'Assigned to Charlie Brown (Billing).' },
    ],
  },
  {
    id: 'TKT-003',
    subject: 'Feature request: Dark mode',
    description: 'I love using your app, but my eyes hurt at night. It would be great if you could add a dark mode option. Thanks!',
    customerName: 'Jane Smith',
    customerEmail: 'jane.s@example.com',
    status: 'closed',
    urgency: 'low',
    category: 'Feature Request',
    createdAt: '2024-08-09T14:00:00Z',
    logs: [
      { id: 'log-3-1', timestamp: '2024-08-09T14:00:00Z', actor: 'AI', actorName: 'TriageFlow AI', action: 'Ticket Created', details: 'Received from web form.' },
      { id: 'log-3-2', timestamp: '2024-08-09T14:01:00Z', actor: 'AI', actorName: 'TriageFlow AI', action: 'Intent Analysis', details: 'Intent: Feature Request, Urgency: Low' },
      { id: 'log-3-3', timestamp: '2024-08-09T14:02:00Z', actor: 'AI', actorName: 'TriageFlow AI', action: 'Auto-response & Close', details: 'Sent thank you for feedback and closed ticket.' },
    ],
  },
  {
    id: 'TKT-004',
    subject: 'Website is down',
    description: 'I can\'t access your website, it shows a 500 server error. Is there an outage?',
    customerName: 'Bob Johnson',
    customerEmail: 'bob.j@example.com',
    status: 'open',
    urgency: 'high',
    category: 'Technical',
    assignedTo: users[1],
    team: teams[0],
    createdAt: '2024-08-11T08:00:00Z',
    logs: [
      { id: 'log-4-1', timestamp: '2024-08-11T08:00:00Z', actor: 'AI', actorName: 'TriageFlow AI', action: 'Ticket Created', details: 'Received from email.' },
      { id: 'log-4-2', timestamp: '2024-08-11T08:01:00Z', actor: 'AI', actorName: 'TriageFlow AI', action: 'Intent Analysis', details: 'Intent: Outage Report, Urgency: High, Category: Technical' },
      { id: 'log-4-3', timestamp: '2024-08-11T08:02:00Z', actor: 'AI', actorName: 'TriageFlow AI', action: 'Route Ticket', details: 'Assigned to Bob Williams (Technical Support).' },
    ],
  },
    {
    id: 'TKT-005',
    subject: 'Pricing clarification for enterprise plan',
    description: 'Could you provide more details on the enterprise plan pricing? We are a team of 100+ and need advanced features.',
    customerName: 'Samantha Ray',
    customerEmail: 'samantha.r@example.com',
    status: 'in_progress',
    urgency: 'medium',
    category: 'Sales',
    assignedTo: users[3],
    team: teams[2],
    createdAt: '2024-08-11T09:15:00Z',
    logs: [
      { id: 'log-5-1', timestamp: '2024-08-11T09:15:00Z', actor: 'AI', actorName: 'TriageFlow AI', action: 'Ticket Created', details: 'Received from API.' },
      { id: 'log-5-2', timestamp: '2024-08-11T09:16:00Z', actor: 'AI', actorName: 'TriageFlow AI', action: 'Intent Analysis', details: 'Intent: Sales Inquiry, Urgency: Medium, Category: Sales' },
      { id: 'log-5-3', timestamp: '2024-08-11T09:17:00Z', actor: 'AI', actorName: 'TriageFlow AI', action: 'Route Ticket', details: 'Assigned to Diana Prince (Sales).' },
    ],
  },
];
